GET https://6ffkixdkeg.execute-api.us-west-1.amazonaws.com/prod/spaces
###

POST https://6ffkixdkeg.execute-api.us-west-1.amazonaws.com/prod/spaces
content-type: application/json

  {
    "location": "Paris"
  }
###

// Query String parameter to retrieve specific ID
GET https://6ffkixdkeg.execute-api.us-west-1.amazonaws.com/prod/spaces?id=343345
###